############################ General data configurations ############################
train_t_gcn:
  type: bool
  default: true
  help: whether to train T-GCN model (Temporal Graph Convolutional Network)
  
train_ast_gcn:
  type: bool
  default: false
  help: whether to train AST-GCN model (Attribute-Augmented Spatiotemporal Graph Convolutional Network)

adjdata:
  type: str
  default: 'data/Graph Neural Network Data/Adjacency Matrix/adj_mx.pkl'  #DataNew
  help: adj data path

lambda_loss:
  type: float
  default: 0.0015
  help: Hyperparameter that controls the strength of the L2 regularization applied to the trainable variables in the model.

learning_rate:  
  type: float
  default: 0.001
  help: Initial learning rate.

training_epoch:
  type: int
  default : 2
  help :  Number of epochs to train. 
  
gru_units : 
  type :  int  
  default : 128 
  help :  hidden units of gru. 
  
seq_len :
  type :  int  
  default : 10 
  help :  time length of inputs. 
      
pre_len :
  type :  int  
  default : 3 
  help :  the number of time steps to predict into the future (time length of prediction).  
      
train_rate :
  type :  float  
  default : 0.8 
  help :  rate of training set. 
      
batch_size :
  type :  int  
  default : 64 
  help :  batch size. 
      
dataset :
  type :  str  
  default :  sz  
  help :  dataset 
      
scheme :
  type :  str  
  default :  1  
  help :  scheme 
      
noise_name :
  type :  str  
  default :  None  
  help :  None or Gauss or Possion 
      
noise_param :
  type :  int  
  default : 0 
  help :  Parameter for noise 
      
dim :
  type :  int  
  default : 64 # was 20 for Unit classes in acell.py
  help :  hidden dimension of the first STGCN layer. 