############################ Experimentation configurations ############################
train_ast_gcn:
  type: bool
  default: true
  help: whether to train AST-GCN model (Attribute-Augmented Spatiotemporal Graph Convolutional Network)
eval_ast_gcn:
  type: bool
  default: false
  help: whether to evaluate AST-GCN model 
hpo_ast_gcn: 
  type: bool
  default: false
  help: whether to perform HPO AST-GCN model 

############################ Visualise Adjacency Matrix ############################
vis:
  type: bool
  default: false
  help: whether to create visualisations
modelVis:
  type: str
  default: GWN
  help: the model to visualise
horizonVis:
  type: str
  default: "3"
  help: the horizon to visualise
splitVis:
  type: str
  default: 1
  help: the split number up to which visualisations should be generated for
locations_path:
  type: str
  default: 'data/Locations/Locations.csv'
  help: path to csv containg station coordinates

############################ General data configurations ############################
forecasting_horizons:
  type: int[]
  # default: [3]
  default: [3,6,9,12,24]
  help: forecast horizons for time step forecasting

stations:
  type: str[]
  default: ['ADDO ELEPHANT PARK', 'ALEXANDERBAAI', 'ALIWAL-NORTH PLAATKOP', 'BARKLY-OOS (CAERLEON)',
                'BRANDVLEI', 'CALVINIA WO', 'CAPE TOWN WO', 'DE AAR WO', 'DOHNE - AGR', 'EAST LONDON WO',
                'EXCELSIOR CERES', 'FORT BEAUFORT', 'FRASERBURG', 'GEORGE WITFONTEIN', 'GEORGE WO', 
                'GRAAFF - REINET', 'GRAHAMSTOWN', 'KOINGNAAS', 'LADISMITH', 'LAINGSBURG', 'LANGGEWENS',
                'MALMESBURY', 'MOLTENO RESERVOIR','NOUPOORT','OUDTSHOORN', 'PATENSIE','POFADDER', 
                'PORT ALFRED - AIRPORT','PORT ELIZABETH AWOS', 'PORT ELIZABETH AWS','PORT NOLLOTH','PORTERVILLE', 
                'PRIESKA', 'REDELINGSHUYS-AWS','RIVERSDALE','SOMERSET EAST','SPRINGBOK WO','TWEE RIVIEREN',
                'UITENHAGE','UPINGTON WO', 'VANWYKSVLEI','VIOOLSDRIF - AWS','VREDENDAL','WILLOWMORE','WORCESTER-AWS']
  # default: ['ADDO ELEPHANT PARK', 'ALEXANDERBAAI', 'ALIWAL-NORTH PLAATKOP', 'BARKLY-OOS (CAERLEON)']
  help: list of all stations names

increment: 
  type: int[]
  # default: [8760, 10920, 13106, 15312, 17520, 19704, 21888, 24096, 26304,
                #  28464, 30648, 32856, 35064, 37224, 39408, 41616, 43824, 45984,
                #  48168, 50376, 52584, 54768, 56952, 59160, 61368, 63528, 65712,
                #  67920, 70128, 72288, 74472, 76680, 78888, 81048, 83232, 85440,
                #  87648, 89832, 92016, 94224, 96432, 98592, 100776, 102984, 105192,
                #  107352, 109536, 111744, 113929]
  default: [1000, 2000, 3000]
  help:  List of points to split data in train, validation, and test sets for walk-forward validation. The first marker, 
    8784 is one year's worth of data, the next step is 3 months of data, and the following step is also 3 months of 
    data, resulting in rolling walk-forward validation where the train size increases each increment, with the 
    validation and test sets each being 3 months' worth of data.

n_stations:
  type: int
  default: 45
  help: number of weather stations

num_splits:
  type: int
  default: 1
  help: number of splits in walk-forward validation

time_steps:
  type: int
  default: 10
  help: number of time steps to consider 

adjdata:
  type: str
  default: 'data/Graph Neural Network Data/Adjacency Matrix/adj_mx.pkl'  #DataNew
  help: adj data path

# lambda_loss:
#   type: float
#   default: 0.0015
#   help: Hyperparameter that controls the strength of the L2 regularization applied to the trainable variables in the model.

# learning_rate:  
#   type: float
#   default: 0.001
#   help: Initial learning rate.

# seq_len :
#   type :  int  
#   default : 10 
#   help :  time length of inputs. 
      
# pre_len :
#   type :  int  
#   default : 3 
#   help :  the number of time steps to predict into the future (time length of prediction).  
      
# train_rate :
#   type :  float  
#   default : 0.8 
#   help :  rate of training set. 
      

####### HPO parameters

num_configs:
  type: int
  default: 30
  help: number of random configurations to search through

batch_size :
  type :  int  
  default : 64
  help :  batch size. 

training_epoch:
  type: int
  default : 20
  help :  Number of epochs to train. 

gru_units: 
  type : int  
  default : 63
  help : hidden units of gru. 

lstm_neurons:
  type : int  
  default : 32 
  help :  Number of recurrent units or neurons in the LSTM layer. 